version: "3.8"
services:
  mongo:
    container_name: mongo
    image: mongo:4-xenial
    hostname: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - node_network
  redis:
    container_name: redis
    image: redis:5
    ports:
     - 6379:6379
    networks:
      - node_network
  node-service:
    container_name: node-server
    image: node-server:1.0
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    environment:
      - NAME=Docker
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - node_network
networks:
  node_network:

volumes:
  mongo: